<a href="https://colab.research.google.com/github/HeHeHuang/DeepLearningNLP/blob/main/DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Deep Learning


## MLP


### Demo

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
X = [[0.,0.],[1.,1.],[2.,2.]]
y = [0,1,1]


In [ ]:
X,y

([[0.0, 0.0], [1.0, 1.0]], [0, 1])

(5,2) 2 dimension set 
2 layers
5 nodes for 1st hidden layer
2 nodes for 2st hidden layer

In [ ]:
clf = MLPClassifier(solver='sgd',alpha = 1e-5,hidden_layer_sizes=(5,2),random_state=1)

In [ ]:
clf.fit(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='sgd')

1. set max_iter increase 
2. tol = 0.000001


In [ ]:
clf = MLPClassifier(solver='sgd',alpha = 1e-5,max_iter = 3000,hidden_layer_sizes=(5,2),random_state=1)
clf.fit(X,y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), max_iter=3000,
              random_state=1, solver='sgd')

In [ ]:
 batch_size = 200  
 shuffle = Ture


> regression: fitting the data

>classification: find the classifying boundary 


In [ ]:
clf.predict([[2.,2.],[-1,-2]])

array([1, 0])

In [ ]:
clf.predict([[2.,2.] ])

In [ ]:
[coef.shape for coef in clf.coefs_]

[(2, 5), (5, 2), (2, 1)]

In [ ]:
clf.predict_proba([[2,2],[1,2]])

array([[0.15882012, 0.84117988],
       [0.15882012, 0.84117988]])

### practical Case with SkLearn

In [ ]:
#/content/drive/MyDrive/Colab Notebooks/concrete.csv
import pandas as pd
from sklearn.neural_network import MLPRegressor
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/concrete.csv')
df


cement   slag    ash  water  superplastic  coarseagg  fineagg  age  \
0      141.3  212.0    0.0  203.5           0.0      971.8    748.5   28   
1      168.9   42.2  124.3  158.3          10.8     1080.8    796.2   14   
2      250.0    0.0   95.7  187.4           5.5      956.9    861.2   28   
3      266.0  114.0    0.0  228.0           0.0      932.0    670.0   28   
4      154.8  183.4    0.0  193.3           9.1     1047.4    696.7   28   
...      ...    ...    ...    ...           ...        ...      ...  ...   
1025   135.0    0.0  166.0  180.0          10.0      961.0    805.0   28   
1026   531.3    0.0    0.0  141.8          28.2      852.1    893.7    3   
1027   276.4  116.0   90.3  179.6           8.9      870.1    768.3   28   
1028   342.0   38.0    0.0  228.0           0.0      932.0    670.0  270   
1029   540.0    0.0    0.0  173.0           0.0     1125.0    613.0    7   

      strength  
0        29.89  
1        23.51  
2        29.22  
3        45.85  
4        18.29  
...        ...  
1025     13.29  
1026     41.30  
1027     44.28  
1028     55.06  
1029     52.61  

[1030 rows x 9 columns]

for machine learning:
>for features selection 

In [ ]:
df.describe()

cement         slag          ash        water  superplastic  \
count  1030.000000  1030.000000  1030.000000  1030.000000   1030.000000   
mean    281.167864    73.895825    54.188350   181.567282      6.204660   
std     104.506364    86.279342    63.997004    21.354219      5.973841   
min     102.000000     0.000000     0.000000   121.800000      0.000000   
25%     192.375000     0.000000     0.000000   164.900000      0.000000   
50%     272.900000    22.000000     0.000000   185.000000      6.400000   
75%     350.000000   142.950000   118.300000   192.000000     10.200000   
max     540.000000   359.400000   200.100000   247.000000     32.200000   

         coarseagg      fineagg          age     strength  
count  1030.000000  1030.000000  1030.000000  1030.000000  
mean    972.918932   773.580485    45.662136    35.817961  
std      77.753954    80.175980    63.169912    16.705742  
min     801.000000   594.000000     1.000000     2.330000  
25%     932.000000   730.950000     7.000000    23.710000  
50%     968.000000   779.500000    28.000000    34.445000  
75%    1029.400000   824.000000    56.000000    46.135000  
max    1145.000000   992.600000   365.000000    82.600000

##### split training set and test set

In [ ]:
X_train = df.iloc[:800,:-1 ] # better use X instead of x --> X vector of features
X_test = df.iloc[800:,:-1 ] 
y_train = df.iloc[:800,-1: ]
y_test = df.iloc[800:,-1: ] 

In [ ]:
X_test

cement   slag    ash  water  superplastic  coarseagg  fineagg  age
200    166.8  250.2    0.0  203.5           0.0      975.6    692.6   28
201    159.8  250.0    0.0  168.4          12.2     1049.3    688.2   28
202    397.0    0.0    0.0  185.7           0.0     1040.6    734.3    7
203    231.8    0.0  121.6  174.0           6.7     1056.4    778.5  100
204    164.6    0.0  150.4  181.6          11.7     1023.3    728.9   28
...      ...    ...    ...    ...           ...        ...      ...  ...
1025   135.0    0.0  166.0  180.0          10.0      961.0    805.0   28
1026   531.3    0.0    0.0  141.8          28.2      852.1    893.7    3
1027   276.4  116.0   90.3  179.6           8.9      870.1    768.3   28
1028   342.0   38.0    0.0  228.0           0.0      932.0    670.0  270
1029   540.0    0.0    0.0  173.0           0.0     1125.0    613.0    7

[830 rows x 8 columns]

In [ ]:
y_test

strength
0       29.89
1       23.51
2       29.22
3       45.85
4       18.29
..        ...
195     22.44
196     26.77
197     68.10
198     52.91
199     32.33

[200 rows x 1 columns]

#### build MLP Regressor 

In [ ]:
reg = MLPRegressor()
reg.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1599: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPRegressor()

##### two problem here 
1. Maximum iterations (200) reached and the optimization hasn't converged yet. > increase max_iteration

2. A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ),

In [ ]:
y_train = np.array(y_train).ravel()
y_train

array([29.89, 23.51, 29.22, 45.85, 18.29, 21.86, 15.75, 36.64, 21.65,
       28.99, 36.35,  6.94, 27.92, 26.26, 23.89, 49.97, 30.08, 44.86,
       15.04, 25.1 , 13.36, 21.92, 20.42, 33.3 , 31.74, 45.3 , 49.19,
       65.2 , 21.54, 33.8 , 32.04, 39.29, 23.74, 44.52, 37.91, 39.16,
       16.88, 47.71, 17.54, 41.41, 24.28, 60.32, 37.42, 23.52, 59.2 ,
       61.46, 17.2 , 40.68, 49.9 , 33.4 , 49.25, 39.  , 37.27, 39.3 ,
       38.22, 20.28, 48.67, 34.57, 35.23, 42.35, 20.73, 10.38, 37.34,
       54.9 , 41.05, 29.98, 28.63, 44.3 , 52.04, 49.8 , 11.41, 50.46,
       28.1 , 26.92, 45.08, 36.94, 24.13, 19.42, 27.42, 39.15, 28.47,
       31.02, 31.25, 43.06, 12.84, 32.24, 67.57, 26.31, 35.3 , 23.8 ,
       14.59, 55.9 , 21.5 , 41.84,  4.9 , 57.23, 71.3 , 33.4 , 33.4 ,
       36.25, 32.96, 61.89, 36.8 , 53.1 , 11.98, 23.85,  9.74, 14.5 ,
       12.18, 38.63, 55.65, 12.05, 27.68, 31.35, 18.13, 12.79, 37.36,
       39.4 , 29.45, 33.36, 16.26, 39.64, 23.79, 45.94, 61.07, 31.03,
       33.19, 21.86,

In [ ]:
reg2 = MLPRegressor(hidden_layer_sizes=(5,2),solver = 'sgd', max_iter=2000,random_state=40)

In [ ]:
reg2.fit(X_train,y_train)   #2 hidden layer: 5nodes and 2 nodes

MLPRegressor(hidden_layer_sizes=(5, 2), max_iter=2000, random_state=40,
             solver='sgd')

In [ ]:
X_test

cement   slag    ash  water  superplastic  coarseagg  fineagg  age
800    375.0    0.0    0.0  186.0           0.0     1038.0    758.0    7
801    297.2    0.0  117.5  174.8           9.5     1022.8    753.5  100
802    148.5  139.4  108.6  192.7           6.1      892.4    780.0   28
803    272.8  105.1   81.8  209.7           9.0      904.0    679.7   28
804    424.0   22.0  132.0  168.0           8.9      822.0    750.0    3
...      ...    ...    ...    ...           ...        ...      ...  ...
1025   135.0    0.0  166.0  180.0          10.0      961.0    805.0   28
1026   531.3    0.0    0.0  141.8          28.2      852.1    893.7    3
1027   276.4  116.0   90.3  179.6           8.9      870.1    768.3   28
1028   342.0   38.0    0.0  228.0           0.0      932.0    670.0  270
1029   540.0    0.0    0.0  173.0           0.0     1125.0    613.0    7

[230 rows x 8 columns]

In [ ]:
y_prediction= reg2.predict(X_test)


In [ ]:
y_prediction

array([35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44654008,
       35.44654008, 35.44654008, 35.44654008, 35.44654008, 35.44

In [ ]:
len(y_prediction)

230

#### evaluate model


In [ ]:
 mean_squared_error(y_true=y_test,y_pred=y_prediction)


270.298500997026

#### Normalization
> normalize the features:
in sklearn.preprocessing import StandardScaler 
> mean, variance

> import accuracy 


In [ ]:
scale= StandardScaler(with_mean=True,with_std= True)

In [ ]:
X_train_n = scale.fit_transform(X_train)
X_train_n

array([[-1.32367522,  1.61702386, -0.83310929, ..., -0.04672674,
        -0.31363575, -0.28844798],
       [-1.06019885, -0.35098824,  1.12611406, ...,  1.34929609,
         0.27910576, -0.50990516],
       [-0.28599835, -0.84009372,  0.67531931, ..., -0.23755922,
         1.08682479, -0.28844798],
       ...,
       [-0.77667536,  0.69444575, -0.83310929, ...,  0.03780308,
         0.64320064, -0.62063375],
       [-0.54947472, -0.84009372,  0.69108136, ..., -0.10692222,
         1.19990545, -0.68390723],
       [ 0.23904514, -0.84009372,  0.74309614, ..., -0.21066337,
        -0.85418618, -0.28844798]])

In [ ]:
X_test_n = scale.transform(X_test)
X_test_n

array([[ 0.90728232, -0.84009372, -0.83310929, ...,  0.80113299,
        -0.1955845 , -0.62063375],
       [ 0.16458443, -0.84009372,  1.01893209, ...,  0.60645825,
        -0.25150351,  0.85047467],
       [-1.25494226,  0.77557699,  0.87864981, ..., -1.06364612,
         0.07779732, -0.28844798],
       ...,
       [-0.03397747,  0.50436685,  0.59020421, ..., -1.34925446,
        -0.0675921 , -0.28844798],
       [ 0.59225622, -0.39966698, -0.83310929, ..., -0.55646719,
        -1.28911181,  3.53959759],
       [ 2.48241281, -0.84009372, -0.83310929, ...,  1.91538975,
        -1.99741927, -0.62063375]])

In [ ]:
reg3 =MLPRegressor(hidden_layer_sizes=(5,2),solver = 'sgd', max_iter=2000,random_state=40)

In [ ]:
reg3.fit(X_train_n,y_train)

MLPRegressor(hidden_layer_sizes=(5, 2), max_iter=2000, random_state=40,
             solver='sgd')

In [ ]:
y_prediction_n=reg3.predict(X_test_n)

##### the MSE decrease

In [ ]:
mean_squared_error(y_true=y_test,y_pred=y_prediction_n)

49.437998820911794

### Tensorflow 

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.8.2
