<a href="https://colab.research.google.com/github/HeHeHuang/DeepLearningNLP/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TensorFlow
 
https://www.youtube.com/watch?v=tpCFfeUEGs8&t=2893s

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
import numpy as np

## Tensor

check function trick
> Common+shfit+space

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7],[7,10]]
)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
 matrix.ndim

2

### 32 bit precision
> float 16 and int 32, and float 32? 


In [ ]:
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16 )

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [ ]:
tensor = tf.constant([[[1,1],[2,2],[3,3]]])
tensor

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 1],
        [2, 2],
        [3, 3]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### ndim: how many item in the shape
>eg: (1,3,2) 3 dim. (2,2) 2 dim. (3,)1dim

In [ ]:
another_tensor = tf.constant([[[1,2,3],
                               [4,5,6]],
                              [[7,8,9],
                                [10,11,12]],
                              [[13,14,15],
                               [16,17,18]]])  #(3,2,3)

In [ ]:
another_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

#### trick to count the shape
> three bruckt :[[[  3 dim

> from first bruckt: 3 [[, 

> from second bruckt: 2 [[, 2 row

> there are 3 item in [, for column

### creating tensor with `tf.Variable`

In [ ]:
changable_tensor = tf.Variable([7,10])
unchangable_tensor = tf.constant([7,10])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

In [ ]:
changable_tensor[0] = 7

TypeError: ignored

In [ ]:
unchangable_tensor[0] = 7

TypeError: ignored

In [ ]:
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
changable_tensor.assign_add([1,1])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 8, 11], dtype=int32)>

### Creating random tensors

> initialize with random weights


In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproduciability
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42) # set seed for reproduciability
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1 ==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

###Shuffle the order of elements in Tensor  

>why need to do this:?
because the input in order impact the NN's learning, we can shuffle the order to make it more random

In [ ]:
not_shuffle_tensor = tf.constant([[1,2],
                                  [3,4],
                                  [5,6],
                                  [7,8]])
not_shuffle_tensor

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffle_tensor,seed =42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 4],
       [7, 8],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle_tensor,seed =42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2],
       [7, 8]], dtype=int32)>

##### ❓**Question:** random seed geeration: 
global seed & operation-level seed
>https://www.tensorflow.org/api_docs/python/tf/random/set_seed

❓ if you repeat the experiment to find out the parameter, need to set the seed. start with the same weight?  

### other ways to make tensorflow

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
 tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

#### turn numpy to Tensor
main different: tensors can be run on a GPU more faster for the numial computing

In [ ]:
# create numpy by arrage 

In [ ]:
# use tensor.constant to convert the numpy 



In [ ]:
# reshape the array in tensor 

### Getting information from tensors

* Shape
* Rank
* Axis or dim
* Size

In [ ]:
tensor_1 = tf.constant([3,4,5])

In [ ]:
tf.size(tensor_1)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
#shape


In [4]:
#rank
rank_4_tensor =tf.zeros(shape=[2,3,4,5])

In [5]:
rank_4_tensor # with 3 dimension you have 4 elements 

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[0][1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
# Get various attributes of our tensor 
 # datatype, dimensions,shape,elements along , total number

### Indexing tensors
> tensors can be indexed just like python list

In [19]:
# get the first 2 elements of each dimension

some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [20]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [21]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [22]:
rank_4_tensor[:,:,1,1]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [24]:
rank_4_tensor[:1,:1]

<tf.Tensor: shape=(1, 1, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor[1,1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [33]:
rank_3_tensor = tf.zeros(shape=(2,3,4))


The number of dimensions a tensor has is called its rank and the length in each dimension describes its shape.

In [34]:
rank_3_tensor[:,1,:]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [35]:
rank_2_tensor= tf.constant([[10,7],
                           [3,4]])

In [38]:
#get the last item of each of row of our rank 2 tensor 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

#### Add in extra dimension to our rank2 tensor 

In [40]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
rank_3_tensor = rank_2_tensor[:,:,tf.newaxis] 
rank_3_tensor = rank_2_tensor[...,tf.newaxis]  #:,:  = ... all selected
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [47]:
rank_3_tensor = tf.expand_dims(rank_2_tensor,axis=-1)  #axis will decide which dimension you wanna add 

In [48]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [49]:
y_rank_3_tensor = tf.expand_dims(rank_2_tensor,axis=1)
y_rank_3_tensor   # 3 dimension, you have 2 [[]], and then 1 list in the y axis and 2 elements in list

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [50]:
x_rank_3_tensor = tf.expand_dims(rank_2_tensor,axis=-1)
x_rank_3_tensor  

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Tensor operations: manipulating tensors 

#### basic operation
`+`,`-`,`*`,`/`
>scalar * matrix

In [51]:
#original tensor is unchanged

In [52]:
#multiplecat

In [53]:
# substraction

In [54]:
#tensorflow libaray build-in function 


*Note:* better use the build-in function. it is faster in GPU

#### Matrix multiplication
>dot product

>in tensorflow , you can drop ling. directly use tf.matmul 

In [56]:
#matrix multiplication in tensorflow 
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [57]:
tf.matmul(rank_2_tensor,rank_2_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [58]:
rank_2_tensor * rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [59]:
rank_2_tensor @ rank_2_tensor  # in python @ means matmul 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [60]:
# create a tensor(3,2)
X = tf.constant()

# create another (3,2)


TypeError: ignored

In [61]:
#change the shape of Y 


In [62]:
#try the matmul(X,Y)

In [63]:
#transpose
tf.transpose()

TypeError: ignored

In [64]:
#try matrix multiplication with transpose rather than reshape 

**dot product**
* `tf.matmul()`
* `tf.tensordot` 
> a_axes and b_axes

In [66]:
#axes =0 

In [67]:
#axes =1 

#### changing the data type of a tensor 

In [70]:
#create tensor with default datatype 
B =tf.constant([3.8,7.4])
B.dtype

tf.float32

In [75]:
#with int 32 
C = tf.constant([3,7])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7], dtype=int32)>

In [72]:
# convert 32 bit precision to 16 
D = tf.cast(B,dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3.8, 7.4], dtype=float16)>,
 tf.float16)

In [73]:
# Change from int 32 to float 32 

In [78]:
E = tf.cast(C,dtype = tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3., 7.], dtype=float16)>

In [79]:
F = tf.cast(C, dtype = tf.float32)
F

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 7.], dtype=float32)>

**Note:** 16 bit precision take less memory and less computitial 
16 bit memory. faster in 16 

#### Aggregating tensors 
> Aggregating tensors = condensing them from multiple values down to a smaller amount of values 

In [81]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
#get absolute values 

#### forms of aggregation
* max
* min
* mean
* sum


In [84]:
#create random tensor 
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([69,  4, 75,  7, 58, 94, 77, 20, 79, 32, 14, 74, 98, 55, 69, 50, 86,
       12, 29, 84, 49, 56, 54, 40, 13, 98, 57, 55, 79, 32,  6, 70, 68, 51,
       11, 71, 18, 45, 51, 69, 57, 58, 22, 33, 86, 78, 60, 92, 49,  3])>

In [88]:
# mix of tensor
F = tf.reduce_min(E)
F

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [89]:
G = tf.reduce_mean(E)
G

<tf.Tensor: shape=(), dtype=int64, numpy=52>

#### statistics in Tensorflow 


In [90]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=736>

In [98]:
tf.math.reduce_std(E)  # for the complex , complex64, complex 128, input should be float 32, float 64

TypeError: ignored

In [97]:
# find the standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.132717>

### find the positional maximum and minimum

> return the index of maximun from aixe

In [6]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=(50,))
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [8]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [10]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [12]:
tf.math.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [13]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

#### Squeezing a tensor 

> remove single dimension 


In [14]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[1,1,1,1,50]))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [15]:
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

#### One-hot Encoding

In [16]:
some_list = [0,1,2,3]

In [20]:
tf.one_hot(some_list, depth =4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [21]:
tf.one_hot(some_list,depth=4,on_value= 'Y',off_value = 'N')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Y', b'N', b'N', b'N'],
       [b'N', b'Y', b'N', b'N'],
       [b'N', b'N', b'Y', b'N'],
       [b'N', b'N', b'N', b'Y']], dtype=object)>

#### squaring, log ,sqrt

In [23]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [25]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [27]:
tf.sqrt(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [30]:
tf.math.log(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

###Tensor & Numpy