<a href="https://colab.research.google.com/github/HeHeHuang/DeepLearningNLP/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TensorFlow
 
https://www.youtube.com/watch?v=tpCFfeUEGs8&t=2893s

In [3]:
import tensorflow as tf
print(tf.__version__)

2.8.2


## Tensor

check function trick
> Common+shfit+space

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7],[7,10]]
)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
 matrix.ndim

2

### 32 bit precision
> float 16 and int 32, and float 32? 


In [ ]:
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16 )

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [ ]:
tensor = tf.constant([[[1,1],[2,2],[3,3]]])
tensor

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 1],
        [2, 2],
        [3, 3]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### ndim: how many item in the shape
>eg: (1,3,2) 3 dim. (2,2) 2 dim. (3,)1dim

In [ ]:
another_tensor = tf.constant([[[1,2,3],
                               [4,5,6]],
                              [[7,8,9],
                                [10,11,12]],
                              [[13,14,15],
                               [16,17,18]]])  #(3,2,3)

In [ ]:
another_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

#### trick to count the shape
> three bruckt :[[[  3 dim

> from first bruckt: 3 [[, 

> from second bruckt: 2 [[, 2 row

> there are 3 item in [, for column

### creating tensor with `tf.Variable`

In [ ]:
changable_tensor = tf.Variable([7,10])
unchangable_tensor = tf.constant([7,10])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

In [ ]:
changable_tensor[0] = 7

TypeError: ignored

In [ ]:
unchangable_tensor[0] = 7

TypeError: ignored

In [ ]:
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
changable_tensor.assign_add([1,1])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 8, 11], dtype=int32)>

### Creating random tensors

> initialize with random weights


In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproduciability
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42) # set seed for reproduciability
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1 ==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

###Shuffle the order of elements in Tensor  

>why need to do this:?
because the input in order impact the NN's learning, we can shuffle the order to make it more random

In [ ]:
not_shuffle_tensor = tf.constant([[1,2],
                                  [3,4],
                                  [5,6],
                                  [7,8]])
not_shuffle_tensor

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffle_tensor,seed =42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 4],
       [7, 8],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle_tensor,seed =42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2],
       [7, 8]], dtype=int32)>

##### ❓**Question:** random seed geeration: 
global seed & operation-level seed
>https://www.tensorflow.org/api_docs/python/tf/random/set_seed

❓ if you repeat the experiment to find out the parameter, need to set the seed. start with the same weight?  

### other ways to make tensorflow

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
 tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

#### turn numpy to Tensor
main different: tensors can be run on a GPU more faster for the numial computing

In [ ]:
# create numpy by arrage 

In [ ]:
# use tensor.constant to convert the numpy 



In [ ]:
# reshape the array in tensor 

### Getting information from tensors

* Shape
* Rank
* Axis or dim
* Size

In [ ]:
tensor_1 = tf.constant([3,4,5])

In [ ]:
tf.size(tensor_1)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
#shape


In [4]:
#rank
rank_4_tensor =tf.zeros(shape=[2,3,4,5])

In [5]:
rank_4_tensor # with 3 dimension you have 4 elements 

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[0][1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
# Get various attributes of our tensor 
 # datatype, dimensions,shape,elements along , total number

### Indexing tensors
> tensors can be indexed just like python list

In [19]:
# get the first 2 elements of each dimension

some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [20]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [21]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [22]:
rank_4_tensor[:,:,1,1]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [24]:
rank_4_tensor[:1,:1]

<tf.Tensor: shape=(1, 1, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor[1,1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [33]:
rank_3_tensor = tf.zeros(shape=(2,3,4))


The number of dimensions a tensor has is called its rank and the length in each dimension describes its shape.

In [34]:
rank_3_tensor[:,1,:]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [35]:
rank_2_tensor= tf.constant([[10,7],
                           [3,4]])

In [38]:
#get the last item of each of row of our rank 2 tensor 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

#### Add in extra dimension to our rank2 tensor 

In [40]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
rank_3_tensor = rank_2_tensor[:,:,tf.newaxis] 
rank_3_tensor = rank_2_tensor[...,tf.newaxis]  #:,:  = ... all selected
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [47]:
rank_3_tensor = tf.expand_dims(rank_2_tensor,axis=-1)  #axis will decide which dimension you wanna add 

In [48]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [49]:
y_rank_3_tensor = tf.expand_dims(rank_2_tensor,axis=1)
y_rank_3_tensor   # 3 dimension, you have 2 [[]], and then 1 list in the y axis and 2 elements in list

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [50]:
x_rank_3_tensor = tf.expand_dims(rank_2_tensor,axis=-1)
x_rank_3_tensor  

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Tensor operations: manipulating tensors 

#### basic operation
`+`,`-`,`*`,`/`
>scalar * matrix

In [51]:
#original tensor is unchanged

In [52]:
#multiplecat

In [53]:
# substraction

In [54]:
#tensorflow libaray build-in function 


*Note:* better use the build-in function. it is faster in GPU

#### Matrix multiplication
>dot product

>in tensorflow , you can drop ling. directly use tf.matmul 

In [56]:
#matrix multiplication in tensorflow 
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [57]:
tf.matmul(rank_2_tensor,rank_2_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [58]:
rank_2_tensor * rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [59]:
rank_2_tensor @ rank_2_tensor  # in python @ means matmul 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [60]:
# create a tensor(3,2)
X = tf.constant()

# create another (3,2)


TypeError: ignored

In [61]:
#change the shape of Y 


In [62]:
#try the matmul(X,Y)

In [63]:
#transpose
tf.transpose()

TypeError: ignored

In [64]:
#try matrix multiplication with transpose rather than reshape 

**dot product**
* `tf.matmul()`
* `tf.tensordot` 
> a_axes and b_axes

In [66]:
#axes =0 

In [67]:
#axes =1 

#### changing the data type of a tensor 

In [70]:
#create tensor with default datatype 
B =tf.constant([3.8,7.4])
B.dtype

tf.float32

In [75]:
#with int 32 
C = tf.constant([3,7])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7], dtype=int32)>

In [72]:
# convert 32 bit precision to 16 
D = tf.cast(B,dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3.8, 7.4], dtype=float16)>,
 tf.float16)

In [73]:
# Change from int 32 to float 32 

In [78]:
E = tf.cast(C,dtype = tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3., 7.], dtype=float16)>

In [79]:
F = tf.cast(C, dtype = tf.float32)
F

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 7.], dtype=float32)>

**Note:** 16 bit precision take less memory and less computitial 
16 bit memory. faster in 16 

#### Aggregating tensors 
