<a href="https://colab.research.google.com/github/HeHeHuang/DeepLearningNLP/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TensorFlow
 
https://www.youtube.com/watch?v=tpCFfeUEGs8&t=2893s

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


## Tensor

check function trick
> Common+shfit+space

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7],[7,10]]
)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
 matrix.ndim

2

### 32 bit precision
> float 16 and int 32, and float 32? 


In [ ]:
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16 )

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [ ]:
tensor = tf.constant([[[1,1],[2,2],[3,3]]])
tensor

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 1],
        [2, 2],
        [3, 3]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### ndim: how many item in the shape
>eg: (1,3,2) 3 dim. (2,2) 2 dim. (3,)1dim

In [ ]:
another_tensor = tf.constant([[[1,2,3],
                               [4,5,6]],
                              [[7,8,9],
                                [10,11,12]],
                              [[13,14,15],
                               [16,17,18]]])  #(3,2,3)

In [ ]:
another_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

#### trick to count the shape
> three bruckt :[[[  3 dim

> from first bruckt: 3 [[, 

> from second bruckt: 2 [[, 2 row

> there are 3 item in [, for column

### creating tensor with `tf.Variable`

In [ ]:
changable_tensor = tf.Variable([7,10])
unchangable_tensor = tf.constant([7,10])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

In [ ]:
changable_tensor[0] = 7

TypeError: ignored

In [ ]:
unchangable_tensor[0] = 7

TypeError: ignored

In [ ]:
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
changable_tensor.assign_add([1,1])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 8, 11], dtype=int32)>

### Creating random tensors

> initialize with random weights


In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproduciability
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42) # set seed for reproduciability
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1 ==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

###Shuffle the order of elements in Tensor  

>why need to do this:?
because the input in order impact the NN's learning, we can shuffle the order to make it more random

In [ ]:
not_shuffle_tensor = tf.constant([[1,2],
                                  [3,4],
                                  [5,6],
                                  [7,8]])
not_shuffle_tensor

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffle_tensor,seed =42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 4],
       [7, 8],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle_tensor,seed =42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2],
       [7, 8]], dtype=int32)>

##### ❓**Question:** random seed geeration: 
global seed & operation-level seed
>https://www.tensorflow.org/api_docs/python/tf/random/set_seed

❓ if you repeat the experiment to find out the parameter, need to set the seed. start with the same weight?  

### other ways to make tensorflow

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
 tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

#### turn numpy to Tensor
main different: tensors can be run on a GPU more faster for the numial computing

AttributeError: ignored